# Import Libraries and Fetch Data for EDA:

In [1]:
import numpy as np
import pandas as pd

In [2]:
from data.fetch_data import fetch_ml_data

# EDA on the Fetched Data:

In [3]:
df = fetch_ml_data()
df.head()

,stream_id,niche,country,avg_viewers,peak_viewers,chat_rate,like_count,duration_minutes,stream_donations
0,1,IRL,USA,3202,3862,488,5905,136,442.79
1,2,Music,Canada,3101,4808,308,2341,180,304.37
2,3,Music,Japan,2238,4189,66,5022,182,180.57
3,4,IRL,Canada,2304,4197,354,5497,34,295.50
4,5,Music,India,1297,1710,387,8631,144,685.17

In [5]:
df.drop('stream_id',axis=1,inplace=True)

In [6]:
df.isnull().sum()

niche               0
country             0
avg_viewers         0
peak_viewers        0
chat_rate           0
like_count          0
duration_minutes    0
stream_donations    0
dtype: int64

Here we don't have any missing values for now so it's ok.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   niche             101 non-null    object
 1   country           101 non-null    object
 2   avg_viewers       101 non-null    int64
 3   peak_viewers      101 non-null    int64
 4   chat_rate         101 non-null    int64
 5   like_count        101 non-null    int64
 6   duration_minutes  101 non-null    int64
 7   stream_donations  101 non-null    object
dtypes: int64(5), object(3)
memory usage: 6.4+ KB

Some Columns are objects while others are int we need to convert these objects columns into the int one.

## Converting Categorical Columns into numerical:

In [8]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [9]:
cat_cols = ['niche', 'country']
encoded_data = encoder.fit_transform(df[cat_cols])

In [10]:
encoded_df = pd.DataFrame(
    encoded_data, 
    columns=encoder.get_feature_names_out(cat_cols),
    index=df.index
)

In [11]:
encoded_df

,niche_Education,niche_Finance,niche_Gaming,niche_IRL,niche_Music,niche_Sports,niche_Tech,country_Canada,country_Germany,country_India,country_Japan,country_USA
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
96,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
97,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
98,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
100,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [12]:
df = pd.concat([df.drop(columns=cat_cols), encoded_df], axis=1)

In [13]:
df

,avg_viewers,peak_viewers,chat_rate,like_count,duration_minutes,stream_donations,niche_Education,niche_Finance,niche_Gaming,niche_IRL,niche_Music,niche_Sports,niche_Tech,country_Canada,country_Germany,country_India,country_Japan,country_USA
0,3202,3862,488,5905,136,442.79,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3101,4808,308,2341,180,304.37,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,2238,4189,66,5022,182,180.57,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,2304,4197,354,5497,34,295.50,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1297,1710,387,8631,144,685.17,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,3579,3688,375,2734,30,515.89,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
97,791,2611,433,9972,218,228.23,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
98,174,945,353,5194,142,240.64,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
99,2939,4777,201,4235,215,304.53,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
100,1000,1800,150,200,120,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [14]:
df.isnull().sum()
# If we still doesnt get any missing values we're good to go.

avg_viewers         0
peak_viewers        0
chat_rate           0
like_count          0
duration_minutes    0
stream_donations    0
niche_Education     0
niche_Finance       0
niche_Gaming        0
niche_IRL           0
niche_Music         0
niche_Sports        0
niche_Tech          0
country_Canada      0
country_Germany     0
country_India       0
country_Japan       0
country_USA         0
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   avg_viewers       101 non-null    int64
 1   peak_viewers      101 non-null    int64
 2   chat_rate         101 non-null    int64
 3   like_count        101 non-null    int64
 4   duration_minutes  101 non-null    int64
 5   stream_donations  101 non-null    object
 6   niche_Education   101 non-null    float64
 7   niche_Finance     101 non-null    float64
 8   niche_Gaming      101 non-null    float64
 9   niche_IRL         101 non-null    float64
 10  niche_Music       101 non-null    float64
 11  niche_Sports      101 non-null    float64
 12  niche_Tech        101 non-null    float64
 13  country_Canada    101 non-null    float64
 14  country_Germany   101 non-null    float64
 15  country_India     101 non-null    float64
 16  country_Japan     101 non-null    float64
 17  country_USA       101 non-null    float64
dtypes: float64(12), int64(5), object(1)
memory usage: 14.3+ KB

In [17]:
cols_to_numeric = [
    'stream_donations'
]
for col in cols_to_numeric:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   avg_viewers       101 non-null    int64
 1   peak_viewers      101 non-null    int64
 2   chat_rate         101 non-null    int64
 3   like_count        101 non-null    int64
 4   duration_minutes  101 non-null    int64
 5   stream_donations  101 non-null    float64
 6   niche_Education   101 non-null    float64
 7   niche_Finance     101 non-null    float64
 8   niche_Gaming      101 non-null    float64
 9   niche_IRL         101 non-null    float64
 10  niche_Music       101 non-null    float64
 11  niche_Sports      101 non-null    float64
 12  niche_Tech        101 non-null    float64
 13  country_Canada    101 non-null    float64
 14  country_Germany   101 non-null    float64
 15  country_India     101 non-null    float64
 16  country_Japan     101 non-null    float64
 17  country_USA       101 non-null    float64
dtypes: float64(13), int64(5)
memory usage: 14.3 KB

## Correlation with our label:

In [20]:
corr_mat = df.corr()
donation_corr = corr_mat['stream_donations'].sort_values(ascending=False)

In [21]:
donation_corr

stream_donations    1.000000
niche_Music         0.159193
niche_IRL           0.124217
chat_rate           0.112794
like_count          0.106713
country_USA         0.100128
niche_Finance       0.074091
country_India       0.057735
country_Japan       0.031486
country_Germany    -0.012138
niche_Sports       -0.040279
niche_Education    -0.062696
duration_minutes   -0.100665
niche_Tech         -0.111428
peak_viewers       -0.170806
niche_Gaming       -0.184120
country_Canada     -0.220108
avg_viewers        -0.224630
Name: stream_donations, dtype: float64

# Correlation Matrix Observations:

## 1. Positive Correlation (The Predictors)
These are the signals that suggest a stream is likely to earn more money. When these go up, stream_donations usually goes up.

### niche_Music (+0.16): 
This suggests individual music sessions are quite profitable.

### niche_IRL (+0.12): 
Real Life content is a safe for generating donations.

### chat_rate (+0.11): 
It proves that a "talkative" chat directly correlates with more money.

### like_count (+0.10): 
Streams that get more likes tend to see slightly higher donation totals.

### country_USA (+0.10): 
Streams coming from/targeting the USA are showing a consistent positive trend.

### niche_Finance (+0.07): 
Still in the positive zone.

## 2. Negative Correlation (The Inverse Signals)
Higher values here currently associate with lower donation totals in your specific dataset.

### avg_viewers (-0.22) & peak_viewers (-0.17): 
Massive audiences don't always mean massive donations; smaller, dedicated crowds often donate more per person.

### country_Canada (-0.22): 
At the stream level, it's showing a negative correlation.

### niche_Gaming (-0.18): 
Gaming continues to be a difficult niche for direct donations compared to others.

### niche_Tech (-0.11): 
Shows a slight negative trend at the individual stream level.

### duration_minutes (-0.10): 
This suggests that longer streams don't necessarily lead to more money; quality of time beats quantity of time.

## 3. Uncorrelated (The Noise)
These are very close to zero. The model will likely find these metrics "confusing" because they don't have a clear relationship with the money.

### country_Japan (+0.03): 
Almost no impact on the donation outcome.

### country_Germany (-0.01): 
Perfectly neutral; being in Germany doesn't seem to help or hurt donations here.

### niche_Sports (-0.04): 
Very low correlation, meaning it's not a strong predictor either way right now.

# Columns to Drop:

In [ ]:
# The columns we decided to remove based on low/neutral correlation
COLS_TO_DROP = [
    'stream_id',          # Metadata (just an ID)
    'country_Germany',    # Uncorrelated/Noise
    'country_Japan',      # Uncorrelated/Noise
    'niche_Sports',       # Uncorrelated/Noise
    'niche_Education',    # Low correlation/Noise
    'stream_donations'    # This is the Label (y), must be dropped from Features (X)
]